// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/indian-playlist/IndianPlaylist.tsx": () => import("../components/mockups/indian-playlist/IndianPlaylist.tsx"),
  "./components/mockups/indian-playlist/Scene.tsx": () => import("../components/mockups/indian-playlist/Scene.tsx")
};
